# Generated by Django 4.1.4 on 2022-12-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('can_skip', models.BooleanField(default=False)),
                ('can_queue', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
