# Generated by Django 4.1.4 on 2022-12-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0002_session_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='host',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='password',
            field=models.CharField(default='napalm', max_length=50),
        ),
    ]
