# Generated by Django 4.1.4 on 2022-12-28 20:04

from django.db import migrations, models
import spotify_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_api', '0004_alter_session_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='host',
            field=models.CharField(default='RixRadio', max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='password',
            field=models.CharField(default=spotify_api.models.generate_unique_password, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='votes_to_skip',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
